# Generated by Django 2.2.4 on 2019-11-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chemist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribtion_of_patient', models.TextField(max_length=500)),
                ('name_of_pharmacy', models.CharField(max_length=100)),
            ],
        ),
    ]
